[parity]
chain = "/home/parity/zenchain/zenchain.json"
base_path = "/home/parity/zenchain"

<% if @NODE_ROLE == "PUBLIC_RPC" %>
[rpc]
port = 8545
interface = "all"
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]
<% elsif @NODE_ROLE == "DEPLOYER" %>
[rpc]
port = 8545
interface = "127.0.0.1"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
<% end %>

<% if @NODE_ROLE == "VALIDATOR" %>
[account]
unlock = ["<%= @VALIDATORS[@VALIDATOR_NUM.to_i] %>"]
password = ["/home/parity/zenchain/user.pwds"]
<% elsif @NODE_ROLE == "DEPLOYER" %>
[account]
unlock = ["<%= @DEPLOYERS[@DEPLOYER_NUM.to_i] %>"]
password = ["/home/parity/zenchain/user.pwds"]
<% end %>

<% if @NODE_ROLE == "VALIDATOR" %>
[mining]
engine_signer = "<%= @VALIDATORS[@VALIDATOR_NUM.to_i] %>"
reseal_on_txs = "none"
usd_per_tx = "0"
<% end %>

[network]
port = 30300
min_peers = 25
max_peers = 50
nat = "none"
bootnodes = []
discovery = false
warp = false
snapshot_peers = 0
max_pending_peers = 64
reserved_only = true
reserved_peers = "/home/parity/zenchain/reserved-peers.txt"
