[parity]
chain = "/home/parity/zenchain/zenchain.json"
base_path = "/home/parity/zenchain"
[network]
nat = "none"
port = 30300

<% if @NODE_ROLE == "PUBLIC_RPC" %>
[rpc]
port = 8545
interface = "all"
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]
<% elsif @NODE_ROLE == "PRIVATE_RPC" %>
[rpc]
port = 8545
interface = "127.0.0.1"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
<% end %>

<% if @NODE_ROLE == "VALIDATOR" %>
[account]
unlock = ["<%= @VALIDATORS[@VALIDATOR_NUM.to_i] %>"]
password = ["/home/parity/zenchain/user.pwds"]
[mining]
engine_signer = "<%= @VALIDATORS[@VALIDATOR_NUM.to_i] %>"
reseal_on_txs = "none"
usd_per_tx = "0"
<% end %>

